apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    uid: 'prometheus'
    jsonData:
      httpMethod: POST
      manageAlerts: true
      prometheusType: Prometheus
      prometheusVersion: 2.51.0

  - name: Alertmanager
    type: alertmanager
    access: proxy
    url: http://alertmanager:9093
    uid: 'alertmanager'
    jsonData:
      implementation: prometheus

  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    uid: 'tempo'
    jsonData:
      httpMethod: GET
      tracesToLogs:
        datasourceUid: 'opensearch'
        filterByTraceID: true
        filterBySpanID: true
      tracesToMetrics:
        datasourceUid: 'prometheus'
      serviceMap:
        datasourceUid: 'prometheus'
      nodeGraph:
        enabled: true

  - name: OpenSearch
    type: grafana-opensearch-datasource
    access: proxy
    url: http://opensearch:9200
    jsonData:
      database: "ai-logs"
      flavor: "opensearch"
      timeField: "@timestamp"
      logLevelField: "level"
      logMessageField: "message"
    uid: 'opensearch'
